apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: symfony-demo
spec:
  backoffLimit: 1 # retries could be dangerous for DB migration, maybe should be 0
  template:
    spec:
      containers:
        - name: migrate
          image: symfony-php:2.7.0
          imagePullPolicy: Never # for Minikube, change to Always for production
          # https://symfony.com/doc/current/doctrine.html#migrations-creating-the-database-tables-schema
          command: ["php", "bin/console", "doctrine:migrations:migrate"]
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: symfony-secret
                  key: APP_SECRET
      restartPolicy: Never
