apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: symfony-demo
spec:
  backoffLimit: 1 # retries could be dangerous, maybe should be 0
  template:
    spec:
      containers:
        - name: migrate
          image: symfony-php:latest
          imagePullPolicy: Never
          # https://symfony.com/doc/current/doctrine.html#migrations-creating-the-database-tables-schema
          command: ["php", "bin/console", "doctrine:migrations:migrate"]
      restartPolicy: Never
