apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: symfony-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: symfony-php:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: symfony-secret
                  key: APP_SECRET
