apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: symfony-demo
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: symfony-php:v2.7.0
          imagePullPolicy: Never # for Minikube, change to IfNotPresent for production
          ports:
            - containerPort: 9000
          env:
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: symfony-secret
                  key: APP_SECRET
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # This ensures that at least one pod is always available during updates
      maxSurge: 1
      maxUnavailable: 0
