apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: symfony-demo
spec:
  selector:
    app: php
  ports:
    - port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: symfony-demo
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
